#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Rinus Lai - The Learning Blog

# Short bio or description (displayed in the header)
description: Data Science for Accounting and Finance

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://previews.dropbox.com/p/thumb/ABKtD-ugjt0r7Vwjg6MNNUh5jm5gM6Ldg6shWl8xelmIRmZVlYiMjJcCmqXpO4PLlMIpkNPtmvgS3ph3BYYs8PGZplRHebL4Lpp6L5d64zbAcX3uekuhhBPICvHaGERKXcYuwP3cBPra77Qw5HLcbuhhIIDo0kAsHXAlo8zOgwqmh3m4uMhUkn3ujNU9Of1VhnECwraPeXZtEAxRgVnrJ36LUzSTjVRHc4J-ur0tiIMnOhPu5D6q4XmOVC94Oa4ejGjNe5Pzrk-kDLHjdnHZThJcHRyd5d8hjRwIOuVKS5cn7XiitfoH8KHkVlDL3Z-dRN3Xxan_V1ch8rw39HUg8wVJ2F176xuP7nxtLKNBkceyaQ/p.png?fv_content=true&size_mode=5

#RSS Feed params
#plugins:
#  - jekyll-feed
#title: Rinus Lai Blog
#description: Welcome to my blog
#author: Rinus Lai
#https://dzhavat.github.io/2020/01/19/adding-an-rss-feed-to-github-pages.html

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: contactblog@rinuslai.com
  facebook:
  flickr:
  github: 
  instagram: rinus22
  linkedin: rinuslai
  pinterest:
  rss: # rinuslaiRSS
  twitter: rinuslai
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-E0NXVM54ZB

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.rinuslai.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "http://www.rinuslai.com"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-tactile
